upgrades = {
  jumpBoost = {
    title = "JUMP SERVOS",
    desc = "INCREASES JUMP FORCE,\nLETTING YOU JUMP HIGHER IN\nSTRONG GRAVITY."
  };
  timeSlow = {
    title = "IMPROVED PROCESSOR",
    desc = "IMPROVES YOUR PROCESSING\nSPEED, ESSENTIALLY SLOWING\nDOWN TIME FROM YOUR\nPERSPECTIVE.\nPRESS Q TO TOGGLE."
  };
  sprint = {
    title = "PROPULSION CAPACITORS",
    desc = "ALLOWS YOU A QUICK BURST\nOF SPEED: HOLD SHIFT TO\nACCELERATE. MORE UPGRADES\nLET YOU STAY AT HIGH SPEED\nFOR LONGER."
  };
  doubleJump = {
    title = "RCS THRUSTERS",
    desc = "ALLOWS YOU TO 'JUMP' IN\nMID-AIR. MORE UPGRADES LET\nYOU JUMP MORE TIMES BEFORE\nYOU TOUCH THE GROUND."
  };
  
}